1. 유행 현상 해부
    - 왜 해야함?
        - 5월 현상의 규모를 정량화해야 스토리 시작 가능
        - "전체 가입자의 70%가 5월에 가입" 같은 임팩트 있는 숫자 필요
    - 5월 가입자가 전체의 몇 %?
    - 현재 활성 사용자 비율

1. 서비스 확산 패턴 확인
    - 왜 해야함?
        - 바이럴의 핵심은 "어떻게 퍼졌나"
        - 지리적 인접성 vs 소셜 연결성 파악
        - 향후 마케팅 전략의 기초 데이터
    - 학교별 확산 네트워크 분석(거리, 관계)
        - '시작_학교': '어느 학교에서 시작?’
        - '확산_순서': '학교 A → B → C 순서’
        - '확산_속도': '학교간 전파 소요 일수’
        - '지리적_관계': '가까운 학교끼리 퍼졌나?’
        - 사용자의 가입 시기별 학교 위치
    - 시간대별 가입자 급증 포인트
    - 초기 사용자의 영향력 →
        - 인기쟁이(친구 많은놈) 출몰 전후 해당 학교 가입율 비교

In [1]:
import os
import pandas as pd
from google.cloud import storage

# GCS에서 Parquet 파일 불러오기
hackle_events = pd.read_parquet("gs://sprintda05_final_project/processed/hackle_events_processed.parquet", engine='pyarrow')
hackle_device_properties = pd.read_parquet("gs://sprintda05_final_project/hackle/device_properties.parquet", engine='pyarrow')
hackle_user_properties = pd.read_parquet("gs://sprintda05_final_project/hackle/user_properties.parquet", engine='pyarrow')
hackle_properties = pd.read_parquet("gs://sprintda05_final_project/hackle/hackle_properties.parquet", engine='pyarrow')

# 저장할 디렉토리 경로
save_directory = "/home/jovyan/work/data"

# 디렉토리가 존재하지 않으면 생성
os.makedirs(save_directory, exist_ok=True)

# CSV 파일로 저장
hackle_events.to_csv(os.path.join(save_directory, "hackle_events_processed.csv"), index=False)
hackle_device_properties.to_csv(os.path.join(save_directory, "hackle_device_properties.csv"), index=False)
hackle_user_properties.to_csv(os.path.join(save_directory, "hackle_user_properties.csv"), index=False)
hackle_properties.to_csv(os.path.join(save_directory, "hackle_properties.csv"), index=False)

print("모든 파일이 성공적으로 CSV로 저장되었습니다:")
print(f"- hackle_events_processed.csv")
print(f"- hackle_device_properties.csv") 
print(f"- hackle_user_properties.csv")
print(f"- hackle_properties.csv")
print(f"저장 위치: {save_directory}")

모든 파일이 성공적으로 CSV로 저장되었습니다:
- hackle_events_processed.csv
- hackle_device_properties.csv
- hackle_user_properties.csv
- hackle_properties.csv
저장 위치: /home/jovyan/work/data

In [2]:
import os
import pandas as pd
from google.cloud import storage

# GCS에서 Parquet 파일 불러오기 (votes 관련 데이터)
accounts_attendance = pd.read_parquet("gs://sprintda05_final_project/votes/accounts_attendance.parquet", engine='pyarrow')
accounts_blockrecord = pd.read_parquet("gs://sprintda05_final_project/processed/accounts_blockrecord_processed.parquet", engine='pyarrow')
accounts_failpaymenthistory = pd.read_parquet("gs://sprintda05_final_project/votes/accounts_failpaymenthistory.parquet", engine='pyarrow')
accounts_friendrequest = pd.read_parquet("gs://sprintda05_final_project/votes/accounts_friendrequest.parquet", engine='pyarrow')
accounts_group = pd.read_parquet("gs://sprintda05_final_project/votes/accounts_group.parquet", engine='pyarrow')
accounts_nearbyschool = pd.read_parquet("gs://sprintda05_final_project/votes/accounts_nearbyschool.parquet", engine='pyarrow')
accounts_paymenthistory = pd.read_parquet("gs://sprintda05_final_project/votes/accounts_paymenthistory.parquet", engine='pyarrow')
accounts_user_contacts = pd.read_parquet("gs://sprintda05_final_project/votes/accounts_user_contacts.parquet", engine='pyarrow')
accounts_pointhistory = pd.read_parquet("gs://sprintda05_final_project/votes/accounts_pointhistory.parquet", engine='pyarrow')
accounts_school = pd.read_parquet("gs://sprintda05_final_project/votes/accounts_school.parquet", engine='pyarrow')
accounts_timelinereport = pd.read_parquet("gs://sprintda05_final_project/votes/accounts_timelinereport.parquet", engine='pyarrow')
accounts_user = pd.read_parquet("gs://sprintda05_final_project/processed/accounts_user_processed.parquet", engine='pyarrow')
accounts_userquestionrecord = pd.read_parquet("gs://sprintda05_final_project/processed/accounts_userquestionrecord_processed.parquet", engine='pyarrow')
accounts_userwithdraw = pd.read_parquet("gs://sprintda05_final_project/votes/accounts_userwithdraw.parquet", engine='pyarrow')
event_receipts = pd.read_parquet("gs://sprintda05_final_project/votes/event_receipts.parquet", engine='pyarrow')
events = pd.read_parquet("gs://sprintda05_final_project/votes/events.parquet", engine='pyarrow')
polls_question = pd.read_parquet("gs://sprintda05_final_project/votes/polls_question.parquet", engine='pyarrow')
polls_questionpiece = pd.read_parquet("gs://sprintda05_final_project/votes/polls_questionpiece.parquet", engine='pyarrow')
polls_questionreport = pd.read_parquet("gs://sprintda05_final_project/votes/polls_questionreport.parquet", engine='pyarrow')
polls_questionset = pd.read_parquet("gs://sprintda05_final_project/votes/polls_questionset.parquet", engine='pyarrow')
polls_usercandidate = pd.read_parquet("gs://sprintda05_final_project/votes/polls_usercandidate.parquet", engine='pyarrow')

# 저장할 디렉토리 경로
save_directory = "/home/jovyan/work/data"

# 디렉토리가 존재하지 않으면 생성
os.makedirs(save_directory, exist_ok=True)

# CSV 파일로 저장
accounts_attendance.to_csv(os.path.join(save_directory, "accounts_attendance.csv"), index=False)
accounts_blockrecord.to_csv(os.path.join(save_directory, "accounts_blockrecord_processed.csv"), index=False)
accounts_failpaymenthistory.to_csv(os.path.join(save_directory, "accounts_failpaymenthistory.csv"), index=False)
accounts_friendrequest.to_csv(os.path.join(save_directory, "accounts_friendrequest.csv"), index=False)
accounts_group.to_csv(os.path.join(save_directory, "accounts_group.csv"), index=False)
accounts_nearbyschool.to_csv(os.path.join(save_directory, "accounts_nearbyschool.csv"), index=False)
accounts_paymenthistory.to_csv(os.path.join(save_directory, "accounts_paymenthistory.csv"), index=False)
accounts_user_contacts.to_csv(os.path.join(save_directory, "accounts_user_contacts.csv"), index=False)
accounts_pointhistory.to_csv(os.path.join(save_directory, "accounts_pointhistory.csv"), index=False)
accounts_school.to_csv(os.path.join(save_directory, "accounts_school.csv"), index=False)
accounts_timelinereport.to_csv(os.path.join(save_directory, "accounts_timelinereport.csv"), index=False)
accounts_user.to_csv(os.path.join(save_directory, "accounts_user_processed.csv"), index=False)
accounts_userquestionrecord.to_csv(os.path.join(save_directory, "accounts_userquestionrecord_processed.csv"), index=False)
accounts_userwithdraw.to_csv(os.path.join(save_directory, "accounts_userwithdraw.csv"), index=False)
event_receipts.to_csv(os.path.join(save_directory, "event_receipts.csv"), index=False)
events.to_csv(os.path.join(save_directory, "events.csv"), index=False)
polls_question.to_csv(os.path.join(save_directory, "polls_question.csv"), index=False)
polls_questionpiece.to_csv(os.path.join(save_directory, "polls_questionpiece.csv"), index=False)
polls_questionreport.to_csv(os.path.join(save_directory, "polls_questionreport.csv"), index=False)
polls_questionset.to_csv(os.path.join(save_directory, "polls_questionset.csv"), index=False)
polls_usercandidate.to_csv(os.path.join(save_directory, "polls_usercandidate.csv"), index=False)

print("모든 votes 관련 파일이 성공적으로 CSV로 저장되었습니다:")
print("- accounts_attendance.csv")
print("- accounts_blockrecord_processed.csv")
print("- accounts_failpaymenthistory.csv")
print("- accounts_friendrequest.csv")
print("- accounts_group.csv")
print("- accounts_nearbyschool.csv")
print("- accounts_paymenthistory.csv")
print("- accounts_user_contacts.csv")
print("- accounts_pointhistory.csv")
print("- accounts_school.csv")
print("- accounts_timelinereport.csv")
print("- accounts_user_processed.csv")
print("- accounts_userquestionrecord_processed.csv")
print("- accounts_userwithdraw.csv")
print("- event_receipts.csv")
print("- events.csv")
print("- polls_question.csv")
print("- polls_questionpiece.csv")
print("- polls_questionreport.csv")
print("- polls_questionset.csv")
print("- polls_usercandidate.csv")
print(f"\n총 21개 파일이 저장되었습니다.")
print(f"저장 위치: {save_directory}")

모든 votes 관련 파일이 성공적으로 CSV로 저장되었습니다:
- accounts_attendance.csv
- accounts_blockrecord_processed.csv
- accounts_failpaymenthistory.csv
- accounts_friendrequest.csv
- accounts_group.csv
- accounts_nearbyschool.csv
- accounts_paymenthistory.csv
- accounts_user_contacts.csv
- accounts_pointhistory.csv
- accounts_school.csv
- accounts_timelinereport.csv
- accounts_user_processed.csv
- accounts_userquestionrecord_processed.csv
- accounts_userwithdraw.csv
- event_receipts.csv
- events.csv
- polls_question.csv
- polls_questionpiece.csv
- polls_questionreport.csv
- polls_questionset.csv
- polls_usercandidate.csv

총 21개 파일이 저장되었습니다.
저장 위치: /home/jovyan/work/data

In [1]:
import pandas as pd

# 저장경로
base_path = '/home/jovyan/work/data'

# accounts_user 데이터 불러오기
accounts_user = pd.read_csv(f'{base_path}/accounts_user_processed.csv')

# accounts_userwithdraw 데이터 불러오기
accounts_userwithdraw = pd.read_csv(f'{base_path}/accounts_userwithdraw.csv')

In [2]:
accounts_user

,id,is_superuser,is_staff,gender,point,friend_id_list,is_push_on,created_at,block_user_id_list,hide_user_id_list,...,report_count,alarm_count,pending_chat,pending_votes,group_id,friend_count,is_point_specialist,is_friend_specialist,is_specialist,specialist_type
0,831956,1,1,NaN,600,"[1292473, 913158, 1488461, 1064695, 1043565, 1...",0,2023-03-29 03:44:14.047130,[],[],...,0,0,0,0,NaN,6,False,False,False,normal
1,831962,0,0,F,2248,"[833025, 832642, 982531, 879496, 838541, 83752...",1,2023-03-29 05:18:56.162368,[],[],...,253,40878,5499,110,12.0,43,False,False,False,normal
2,832151,0,0,M,1519,"[838785, 982531, 882567, 879496, 838541, 83649...",0,2023-03-29 12:56:34.989468,[],[],...,0,37,0,47,1.0,51,False,False,False,normal
3,832340,0,0,F,57,"[841345, 982531, 838785, 963714, 882567, 83252...",1,2023-03-29 12:56:35.020790,[],[],...,0,19,0,21,1.0,57,False,False,False,normal
4,832520,0,0,M,1039,"[874050, 849763, 874212, 844297, 838541, 84004...",0,2023-03-29 12:56:35.049311,[],[],...,0,29,0,15,12.0,18,False,False,False,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
677080,1583729,0,0,M,300,[],1,2024-05-08 21:54:33.621408,[],[],...,0,0,0,0,32442.0,0,False,False,False,normal
677081,1583730,0,0,M,420,"[1109507, 1110921, 1111072, 1110054, 1108393, ...",0,2024-05-09 07:08:11.001817,[],[],...,0,1,0,0,43949.0,21,False,False,False,normal
677082,1583731,0,0,M,300,"[1583732, 1583673]",1,2024-05-09 07:22:19.186439,[],[],...,0,1,0,0,18640.0,2,False,False,False,normal
677083,1583732,0,0,F,300,"[1583673, 1583730, 1583731]",1,2024-05-09 07:22:38.387553,[],[],...,0,0,0,0,18640.0,3,False,False,False,normal
677084,1583733,0,0,F,300,[],0,2024-05-09 08:31:17.710824,[],[],...,0,0,0,0,84546.0,0,False,False,False,normal

In [3]:
accounts_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677085 entries, 0 to 677084
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    677085 non-null  int64
 1   is_superuser          677085 non-null  int64
 2   is_staff              677085 non-null  int64
 3   gender                677083 non-null  object
 4   point                 677085 non-null  int64
 5   friend_id_list        677085 non-null  object
 6   is_push_on            677085 non-null  int64
 7   created_at            677085 non-null  object
 8   block_user_id_list    677085 non-null  object
 9   hide_user_id_list     677085 non-null  object
 10  ban_status            677085 non-null  object
 11  report_count          677085 non-null  int64
 12  alarm_count           677085 non-null  int64
 13  pending_chat          677085 non-null  int64
 14  pending_votes         677085 non-null  int64
 15  group_id              677082 non-null  float64
 16  friend_count          677085 non-null  int64
 17  is_point_specialist   677085 non-null  bool
 18  is_friend_specialist  677085 non-null  bool
 19  is_specialist         677085 non-null  bool
 20  specialist_type       677085 non-null  object
dtypes: bool(3), float64(1), int64(10), object(7)
memory usage: 94.9+ MB

In [4]:
accounts_user['ban_status'].value_counts()

ban_status
N     668432
W       7855
NB       608
RB       190
Name: count, dtype: int64

In [5]:
total_users = len(accounts_user)

In [6]:
# created_at을 datetime으로 변환
accounts_user['created_at'] = pd.to_datetime(accounts_user['created_at'])

# 5월 가입자 필터링
may_users = accounts_user[accounts_user['created_at'].dt.month == 5]
may_user_count = len(may_users)

# 5월 가입자 비율
may_ratio = may_user_count / total_users
print(f'5월 가입자 비율: {may_ratio:.2%} ({may_user_count} / {total_users})')

5월 가입자 비율: 93.87% (635554 / 677085)

In [7]:
withdraw_user_df = accounts_user[accounts_user['ban_status'] == 'W']
withdraw_user_count = len(withdraw_user_df)

In [8]:
# 탈퇴 상태가 기록되어 있다면
withdraw_user_count = len(accounts_user[accounts_user['ban_status'] == '탈퇴'])

In [9]:
active_user_count = total_users - withdraw_user_count
active_ratio = active_user_count / total_users
print(f'현재 활성 사용자 비율: {active_ratio:.2%} ({active_user_count} / {total_users})')

현재 활성 사용자 비율: 100.00% (677085 / 677085)

In [10]:
may_active_user_count = len(may_users[may_users['ban_status'] != '탈퇴'])
may_active_ratio = may_active_user_count / may_user_count
print(f'5월 가입자 중 현재 활성 비율: {may_active_ratio:.2%}')

5월 가입자 중 현재 활성 비율: 100.00%

In [11]:
import pandas as pd

# 데이터 불러오기
user_df = pd.read_csv('/home/jovyan/work/data/accounts_user_processed.csv', parse_dates=['created_at'])
group_df = pd.read_csv('/home/jovyan/work/data/accounts_group.csv')
school_df = pd.read_csv('/home/jovyan/work/data/accounts_school.csv')

In [12]:
# 유저 테이블 + 그룹 정보 조인 → 학교 id 얻기
user_group = pd.merge(user_df, group_df, left_on='group_id', right_on='id', how='left')
user_group = user_group.rename(columns={'school_id': 'school_id'})

# 학교별로 가장 첫 가입 시점 계산
school_first_join = (
    user_group
    .groupby('school_id')['created_at']
    .min()
    .reset_index()
    .rename(columns={'created_at': 'first_join_date'})
)

# 학교 이름, 주소 등 붙이기
school_info = pd.merge(school_first_join, school_df, left_on='school_id', right_on='id', how='left')

# 퍼진 순서대로 정렬
school_info_sorted = school_info.sort_values('first_join_date').reset_index(drop=True)

# 결과 확인
import datetime
school_info_sorted['first_join_date'] = school_info_sorted['first_join_date'].dt.strftime('%Y-%m-%d')
school_info_sorted[['first_join_date', 'school_id', 'address', 'school_type', 'student_count']].head(10)

  first_join_date  school_id       address school_type  student_count
0      2023-03-29        1.0           NaN         NaN            NaN
1      2023-03-31     5464.0       경기도 군포시           H          158.0
2      2023-03-31      314.0  충청남도 천안시 동남구           H          131.0
3      2023-03-31      281.0  충청남도 천안시 서북구           H          347.0
4      2023-03-31      272.0  충청남도 천안시 서북구           H          339.0
5      2023-03-31      289.0  충청남도 천안시 서북구           H          385.0
6      2023-04-01     4523.0       경기도 화성시           H           92.0
7      2023-04-01      268.0  충청남도 천안시 서북구           H          236.0
8      2023-04-01     4732.0       경기도 의왕시           H          220.0
9      2023-04-04       10.0      충청북도 충주시           M          159.0

In [1]:
import pandas as pd
import os

# 저장 위치
save_directory = "/home/jovyan/work/data"

# CSV 파일 경로
events_path = os.path.join(save_directory, 'hackle_events_processed.csv')
device_path = os.path.join(save_directory, 'hackle_device_properties.csv')
user_path = os.path.join(save_directory, 'hackle_user_properties.csv')
properties_path = os.path.join(save_directory, 'hackle_properties.csv')

# 데이터 불러오기
hackle_events = pd.read_csv(events_path)
hackle_device_properties = pd.read_csv(device_path)
hackle_user_properties = pd.read_csv(user_path)
hackle_properties = pd.read_csv(properties_path)

# 확인
print("📂 모든 Hackle 데이터 파일이 성공적으로 로드되었습니다:")
print(f"- hackle_events: {hackle_events.shape}")
print(f"- hackle_device_properties: {hackle_device_properties.shape}")
print(f"- hackle_user_properties: {hackle_user_properties.shape}")
print(f"- hackle_properties: {hackle_properties.shape}")

/tmp/ipykernel_22807/2238888156.py:16: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  hackle_user_properties = pd.read_csv(user_path)

📂 모든 Hackle 데이터 파일이 성공적으로 로드되었습니다:
- hackle_events: (11218354, 11)
- hackle_device_properties: (252380, 4)
- hackle_user_properties: (230819, 5)
- hackle_properties: (525350, 8)

In [2]:
print(len(hackle_events))  # 전체 이벤트 수
print(hackle_user_properties['user_id'].nunique())  # 유저 수

11218354
230819

In [ ]:
# 이벤트 로그 
hackle_events['event_name'].value_counts().head(20).plot(kind='barh')